const SHOW_ALERT = "SHOW_ALERT";
const HIDE_ALERT = "HIDE_ALERT";
const CLEAR_USERS = "CLEAR_USERS";
const GET_REPOS = "GET_REPOS";
const GET_USER = "GET_USER";
const SEARCH_USERS = "SEARCH_USERS";
const SET_LOADING = "SET_LOADING";

export {
  SHOW_ALERT,
  HIDE_ALERT,
  CLEAR_USERS,
  GET_REPOS,
  GET_USER,
  SEARCH_USERS,
  SET_LOADING,
};
